// Code generated by mockery v1.0.0
package mocks

import "github.com/windler/godepg/action"
import mock "github.com/stretchr/testify/mock"

// GraphFilter is an autogenerated mock type for the GraphFilter type
type GraphFilter struct {
	mock.Mock
}

// GetPostNodeFilters provides a mock function with given fields:
func (_m *GraphFilter) GetPostNodeFilters() []action.Matcher {
	ret := _m.Called()

	var r0 []action.Matcher
	if rf, ok := ret.Get(0).(func() []action.Matcher); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]action.Matcher)
		}
	}

	return r0
}

// GetPreNodeFilters provides a mock function with given fields:
func (_m *GraphFilter) GetPreNodeFilters() []action.Matcher {
	ret := _m.Called()

	var r0 []action.Matcher
	if rf, ok := ret.Get(0).(func() []action.Matcher); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]action.Matcher)
		}
	}

	return r0
}
