// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Graph is an autogenerated mock type for the Graph type
type Graph struct {
	mock.Mock
}

// AddDirectedEdge provides a mock function with given fields: from, to, description
func (_m *Graph) AddDirectedEdge(from string, to string, description string) {
	_m.Called(from, to, description)
}

// AddNode provides a mock function with given fields: node
func (_m *Graph) AddNode(node string) {
	_m.Called(node)
}

// GetDependencies provides a mock function with given fields: pkg
func (_m *Graph) GetDependencies(pkg string) []string {
	ret := _m.Called(pkg)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(pkg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetDependents provides a mock function with given fields: pkg
func (_m *Graph) GetDependents(pkg string) []string {
	ret := _m.Called(pkg)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(pkg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// String provides a mock function with given fields:
func (_m *Graph) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
